<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="W10D9RJ693" failures="2" tests="8" name="Learning testNG" time="20.328" errors="0" timestamp="2021-04-08T12:00:25 IST">
  <testcase classname="com.testNG.TC001" name="openUrl" time="2.768"/>
  <testcase classname="com.testNG.TC002" name="addAddress" time="0.002">
    <skipped/>
  </testcase> <!-- addAddress -->
  <testcase classname="com.testNG.TC002" name="addCart" time="0.004">
    <failure type="java.lang.AssertionError" message="fail..">
      <![CDATA[java.lang.AssertionError: fail..
at com.testNG.TC002.addCart(TC002.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- addCart -->
  <testcase classname="com.testNG.TC002" name="openUrl" time="4.854"/>
  <testcase classname="com.testNG.MyRetry" name="test" time="3.199">
    <skipped/>
  </testcase> <!-- test -->
  <testcase classname="com.testNG.MyRetry" name="test" time="1.526">
    <skipped/>
  </testcase> <!-- test -->
  <testcase classname="com.testNG.MyRetry" name="test" time="1.478">
    <skipped/>
  </testcase> <!-- test -->
  <testcase classname="com.testNG.MyRetry" name="test" time="1.204">
    <failure type="java.lang.AssertionError" message="test retry">
      <![CDATA[java.lang.AssertionError: test retry
at com.testNG.MyRetry.test(MyRetry.java:11)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- test -->
</testsuite> <!-- Learning testNG -->
